apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-chat
spec:
  selector:
    matchLabels:
      app: chat-service 
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: ngoctd/ecommerce-chat:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
  - port: 8080
    targetPort: 8080
